Importing the necessary Libraries and modules

In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np, seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score, RocCurveDisplay, classification_report, roc_curve

LOAD THE DATASET.

In [29]:
df = pd.read_csv('/home/izy/Documents/Project/CodeAlpa_Tasks/CreditScore_model/Dataset/Credit Score Classification Dataset.csv')
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000,Master's Degree,Married,2,Owned,High
2,35,Female,75000,Doctorate,Married,1,Owned,High
3,40,Male,125000,High School Diploma,Single,0,Owned,High
4,45,Female,100000,Bachelor's Degree,Married,3,Owned,High

Exploring the data

In [30]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='str')

In [31]:
df.info

<bound method DataFrame.info of      Age  Gender  Income            Education Marital Status  \
0     25  Female   50000    Bachelor's Degree         Single
1     30    Male  100000      Master's Degree        Married
2     35  Female   75000            Doctorate        Married
3     40    Male  125000  High School Diploma         Single
4     45  Female  100000    Bachelor's Degree        Married
..   ...     ...     ...                  ...            ...
159   29  Female   27500  High School Diploma         Single
160   34    Male   47500   Associate's Degree         Single
161   39  Female   62500    Bachelor's Degree        Married
162   44    Male   87500      Master's Degree         Single
163   49  Female   77500            Doctorate        Married

     Number of Children Home Ownership Credit Score
0                     0         Rented         High
1                     2          Owned         High
2                     1          Owned         High
3                     0          Owned         High
4                     3          Owned         High
..                  ...            ...          ...
159                   0         Rented          Low
160                   0         Rented      Average
161                   2          Owned         High
162                   0          Owned         High
163                   1          Owned         High

[164 rows x 8 columns]>

In [32]:
df.describe()

              Age         Income  Number of Children
count  164.000000     164.000000          164.000000
mean    37.975610   83765.243902            0.652439
std      8.477289   32457.306728            0.883346
min     25.000000   25000.000000            0.000000
25%     30.750000   57500.000000            0.000000
50%     37.000000   83750.000000            0.000000
75%     45.000000  105000.000000            1.000000
max     53.000000  162500.000000            3.000000

In [33]:
df.shape

(164, 8)

Converting the non numericall features/columns of our dataset(Gender, Maritial status, Education, Home ownership and credit score) into numerical values which can be used in training and inference of our machine learning model.

In [34]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='str')

In [35]:
df = pd.get_dummies(df, drop_first=True, columns=['Gender','Education','Marital Status', 'Home Ownership','Credit Score'], dtype=int)
df.head()

,Age,Income,Number of Children,Gender_Male,Education_Bachelor's Degree,Education_Doctorate,Education_High School Diploma,Education_Master's Degree,Marital Status_Single,Home Ownership_Rented,Credit Score_High,Credit Score_Low
0,25,50000,0,0,1,0,0,0,1,1,1,0
1,30,100000,2,1,0,0,0,1,0,0,1,0
2,35,75000,1,0,0,1,0,0,0,0,1,0
3,40,125000,0,1,0,0,1,0,1,0,1,0
4,45,100000,3,0,1,0,0,0,0,0,1,0

In [37]:
df.shape

(164, 12)

Updating our intial columns as there is an increase in number of columns after performing one-hotencoding with the get_dummies method. 8 > 12 columns

In [38]:
columns = df.columns

Visualization Of Our dataset